[package]
name = "daikin_exporter"
version = "0.1.0"
edition = "2018"

[dependencies]
prometheus_exporter = "0.8"
env_logger = "0.9"
log = "0.4"
reqwest = { version = "0.11",features = ["blocking"] }
tokio = { version = "1.14.0", features = ["full"] }

